config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/profile_sign_up', to: 'users/registrations#profile_sign_up', :via => [:get], :as => 'profile_sign_up'
  end
  root to: 'pages#home'
  post '/bookmark/:id' => 'offers#bookmark', as: :bookmark
  resources :offers do
    resources :inquiries do
      member do
        get 'create_chat', to: 'chatrooms#create_chatroom'
      end
      resources :interviews, only: [:new, :create]
    end
    resources :reviews
  end
  get '/users/my_interviews', to: 'interviews#my_interviews', as: :my_interviews
  get '/users/my_inquiries', to: 'inquiries#index', as: :my_inquiries
  get 'users/applications', to: 'users#job_offers', as: :business_applications
  get 'users/success', to: 'users#success', as: :inquiry_sent
  get 'users/savedoffers', to: 'users#saved_offers', as: :saved_offers
  get 'users/applications/:id/change_status', to: 'inquiries#change_status', as: :change_status
  resources :users
  resources :contact, only: [:new, :create]
  # resources :about, only: [:show]
  get 'contact_us' => 'pages#contact_us'
  resources :services, only: [:show]
  get 'services' => 'pages#services'
  get 'about' => 'pages#about', as: :about
  resources :customers, only: [:show]
  get 'customers' => 'pages#customers'
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :inquiries
  has_many :messages, dependent: :destroy
  has_many :offers
  has_many :interviews
  has_one_attached :photo
  has_one_attached :business_logo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name
      user.location = auth.extra.raw_info.location
      user.business_name = auth.extra.raw_info.company
      user.bio = auth.extra.raw_info.bio
      user.website = auth.info.urls.GitHub
      user.avatar_url = auth.info.image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in(@user)
      if @user.user_type?
        redirect_to root_path(@user)
      else
        @user.update(user_type: 'Developer')
        redirect_to profile_sign_up_path event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
      end
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # Overwrite update_resource to let users to update their user without giving their password
  def update_resource(resource, params)
    if resource.provider == "github"
      params.delete("current_password")
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  def profile_sign_up
    @user = current_user
    if @user
      render :profile_sign_up
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end

  def after_sign_up_path_for(resource)
    @user = current_user
    @user.update(user_type: 'Business')
    profile_sign_up_path event: :authentication #this will throw if @user is not activated
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def developers
    @developers = User.where(user_type: "developer")
  end

  def businesses
    @businesses = User.where(user_type: "business")
  end

  def success
    @inquiry = current_user.inquiries.last
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@offer)
  end

  def saved_offers
    @offers = Offer.all
    @saved_offers = []
    @offers.each do |offer|
      @saved_offers << offer if offer.saved
    end
  end

  def job_offers
    @job_offers = []
    current_user.offers.each do |offer|
      offer.inquiries.each do |inquiry|
        @job_offers << inquiry
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email, :full_name, :user_type, :bio, :location, :dob,
      :phone_number, :hourly_rate, :headline, :business_address,
      :business_name, :business_vat_id, :business_size, :website,
      :provider, :uid, :avatar_url, :developer_role, :username,
      :linkedin_url, :photo
      )
  end

end

app/views/users/job_offers.html.erb
    
<div class="banner-inquiry-show">
  <div class="banner-container offers" style="color: white;">
    <h2>Welcome, <%=current_user.full_name%> (<%=current_user.business_name%>) &#128188;</h2>
    <h4>These are the applications for your open positions</h4>
  </div>
</div>
<div class="job-offers-container">
  <div class="job-offers">
    <% @job_offers.each do |inquiry| %>
    <div class="courses-container">
      <div class="course">
        <div class="course-preview">
          <h6>Applicant</h6>
          <h2><%= inquiry.user.full_name %></h2>
          <%= link_to user_path(inquiry.user) do%>View Profile<i class="fas fa-chevron-right"></i><%end%>
        </div>
        <div class="course-info">
          <div class="progress-container">
            <span class="progress-text">
              <%= inquiry.created_at %>
            </span>
          </div>
          <h6>Job Title</h6>
          <h2><%= inquiry.offer.title %></h2>
          <span class="progress-text inquiry-status">application status: <%= inquiry.status %></span>
          <%= link_to offer_inquiry_path(inquiry.offer, inquiry), class: "btn inquiry" do %>Details<%end%>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/users/saved_offers.html.erb
<div class="wrapper offers">
  <div class="saved-header">
    <strong><h2 style="text-shadow: 0px 0px 10px black; text-align: center; color: white;">Saved positions</h2></strong>
  </div>
<div class="container offer">
  <div class="offers index">
      <% @saved_offers.reverse.each do |offer| %>
      <div class="card offers mx-auto">
        <div class="row">
          <div class="logo offers ml-3 mb-3"><img
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxDRpxI5gXgaVmnO-VgcVUNOkca91jIpS75Flbzkz5W_5g5_V5&usqp=CAU">
          </div>
          <div class="title-info">
            <div class="card-title" style="margin-bottom: 5px">
              <h6 class="heading" style="color: black;"><%= link_to offer_path(offer) do %>
                <%= offer.title %>
                <% end %></h6>
              </div>
              <div class="offer-details">
               <button type="button" class="btn  btn-sm" style="background: #8B2635; cursor: unset;"><%=offer.employment_type%></button>
               <button type="button" class="btn  btn-sm" style="background: #8B2635; cursor: unset;">
                <%if @fixed_price%>Fixed Price<%else%>Per Hour<%end%></button>
              <button type="button" class="btn  btn-sm" style="background: #8B2635;cursor: unset;"><%=offer.location%></button>
            </div>
          </div>
        </div>
        <p class="text-muted"><%= truncate(offer.description, length:150) %></p>
        <div class="row offer-btn-sbmt btnsubmit mt-4">
          <div style="padding-top: 1rem; padding-left: 0.4rem;"> <%= link_to new_offer_inquiry_path(offer) do %>
            <button name="button" type="submit" class="btn-offer btn1 btn btn-success"><i class="fab fa-telegram-plane"></i>
            Apply</button>
          <% end %></div>
          <div style="padding-top: 1rem; padding-left: 0.4rem;">
          <%= button_to bookmark_path(offer), class: "btn-offer btn-success btn", id: "bookmark-#{offer.id}", method: :post, remote: true do %>
          <i class="fa<%= offer.saved ? 's' : 'r' %> fa-bookmark"></i> Save
          <% end %> </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%if current_user == @user%>
<div class="wrapper-profile">
  <div class="profile-page-container">
    <div class="profile-card gradient-topleft">
      <div class="profile-page-first">
        <div class="profile-page-avatar">
          <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "profile-pic" %>
          <% elsif current_user.avatar_url? %>
          <%= image_tag current_user.avatar_url, class: "profile-pic" %>
          <% else %>
          <%= image_tag "avatar_placeholder.png", class: "profile-pic" %>
          <% end %>
        </div>
        <div class="profile-page-info">
          <ul>
            <li><h2 class="m-0"><%= current_user.full_name %></h2></li>
            <li><p><%= current_user.email %></li>
              <% if current_user.website? %>
              <li><p>🌍 <%= current_user.website %></p></li>
              <% end %>
              <% if current_user.phone_number? %>
              <li><p>📱 <%= current_user.phone_number %></p></li>
              <% end %>
              <% if current_user.hourly_rate? %>
              <li><p>💸 <%= current_user.hourly_rate %>€/h</p></li>
              <% end %>
            </ul>
            <div class="icon-block">
              <a href="<%=current_user.linkedin_url%>"><i class="fab fa-linkedin p-2"></i></a>
              <a href="#"> <i class="fab fa-twitter p-2"></i></a>
              <a href="#"> <i class="fab fa-google-plus p-2"></i></a>
            </div>
            <!-- buttons -->
            <div class="profile-page-button pt-4 border-top">
              <%= link_to edit_user_registration_path, class: "btn nav-item btn-primary" do %>
              Edit Profile
              <% end %>
              <% if current_user.user_type == "Business"%>
              <%= link_to new_offer_path, class: "btn nav-item btn-warning" do %>
              Add Offer
              <%end%>
              <%= link_to business_applications_path, class: "btn nav-item btn-dark" do %>
              Job Applications
              <% end %>
              <%= link_to my_interviews_path, class: "btn nav-item btn-danger" do %>
              Interviews
              <% end %>
              <% else %>
              <%= link_to user_path, class: "btn nav-item btn-success" do %>
              Upload Resume
              <% end %>
              <%= link_to my_inquiries_path, class: "btn nav-item btn-dark" do %>
              My Applications
              <% end %>
              <%= link_to my_interviews_path, class: "btn nav-item btn-danger" do %>
              Interviews
              <% end %>
              <%= link_to saved_offers_path, class: "btn nav-item btn-warning" do %>
              Saved Offers
              <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="card my-4">
        <div class="profile-page-about">
          <h2>Bio</h2>
          <p><%=current_user.bio%></p>
        </div>
      </div>
    </div>
  </div>
  <%else%>
  <div class="wrapper-profile">
    <div class="profile-page-container">
      <div class="profile-card gradient-topleft">
        <div class="profile-page-first">
          <div class="profile-page-avatar">
            <!-- <img src="https://images.unsplash.com/photo-1589329482108-e414c7c6b8c7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" class="profile-pic" > -->
            <%if @user.photo.attached? || !@user.avatar_url.nil?%>
            <%= image_tag @user.avatar_url, class: "profile-pic" %>
            <%end%>
          </div>
          <div class="profile-page-info">
            <ul>
              <li><h2 class="m-0"><%= @user.full_name %></h2></li>
              <li><p><%= @user.email %></li>
                <li>🌍 <%= @user.location %></li>
                <li>📱 <%= @user.phone_number %></li>
                <li><i>Hourly rate</i> <%= @user.hourly_rate %>€/h</li>
              </ul>
              <div class="icon-block">
                <a href="<%=@user.linkedin_url%>"><i class="fab fa-linkedin p-2"></i></a>
                <a href="<%=@user.website%>"> <i class="fab fa-twitter p-2"></i></a>
                <a href="#"> <i class="fab fa-google-plus p-2"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="card my-4">
          <div class="profile-page-about">
            <h2>Bio</h2>
            <p><%=@user.bio%></p>
          </div>
        </div>
      </div>
    </div>
    <%end%>

app/views/users/success.html.erb
<div class="inquiry-wrapper">
  <div class="inquiry-success-container">
    <h3> Congratulations! </h3>
    <p> Your application has been sent to the employer.<br> You will receive a notification as soon as they will answer your inquiry.</p>
    <%= link_to offers_path do %>
      <button name="button" type="submit" class="btn-inquiry btn1 btn btn-success"> Back to browse </button>
    <% end %>
    <%= link_to my_inquiries_path do %>
      <button name="button" type="submit" class="btn-inquiry btn1 btn btn-success"> Check my Inquiries </button>
    <% end %>
  </div>
  <div class="inquiry-message-container">
    <h3> Your Message </h3>
    <p><%= @inquiry.message %></p>
  </div>
  </div>