config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/profile_sign_up', to: 'users/registrations#profile_sign_up', :via => [:get], :as => 'profile_sign_up'
  end
  root to: 'pages#home'
  post '/bookmark/:id' => 'offers#bookmark', as: :bookmark
  resources :offers do
    resources :inquiries do
      member do
        get 'create_chat', to: 'chatrooms#create_chatroom'
      end
      resources :interviews, only: [:new, :create]
    end
    resources :reviews
  end
  get '/users/my_interviews', to: 'interviews#my_interviews', as: :my_interviews
  get '/users/my_inquiries', to: 'inquiries#index', as: :my_inquiries
  get 'users/applications', to: 'users#job_offers', as: :business_applications
  get 'users/success', to: 'users#success', as: :inquiry_sent
  get 'users/savedoffers', to: 'users#saved_offers', as: :saved_offers
  get 'users/applications/:id/change_status', to: 'inquiries#change_status', as: :change_status
  resources :users
  resources :contact, only: [:new, :create]
  # resources :about, only: [:show]
  get 'contact_us' => 'pages#contact_us'
  resources :services, only: [:show]
  get 'services' => 'pages#services'
  get 'about' => 'pages#about', as: :about
  resources :customers, only: [:show]
  get 'customers' => 'pages#customers'
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-container">
    <ul class="foote_bottom_ul_amrc">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to "Contact", contact_us_path %></li>
    </ul>

    <p class="text-center">Copyright @2020 | Designed With ❤️ by <a href="#">Welance</a></p>

    <ul class="social_footer_ul">
      <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
      <li><a href="#"><i class="fab fa-twitter"></i></a></li>
      <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
      <li><a href="#"><i class="fab fa-instagram"></i></a></li>
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="nav global">
	<div class="container navigation-bar">
		<div class="logo">
			<a href="/">Welance</a>
		</div>
		<div id="mainListDiv" class="main_list">
			<ul class="navlinks">
				<%if user_signed_in?%>
        <li><%= link_to 'Offers', offers_path %></li>
        <%end%>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to "Contact", contact_us_path %></li>
        <% unless user_signed_in?%>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <%else%>
        <span class="navbar-toggler-icon"></span>
        <div class="collapse navbar-collapse show" id="navbar-list-4" style="margin-top: -0.5rem;">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

               <% if current_user.photo.attached? %>
               <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, class: "rounded-circle" %>
               <% elsif current_user.avatar_url? %>
               <%= image_tag current_user.avatar_url, width: 40, height: 40, crop: :fill, class: "rounded-circle" %>
               <% else %>
               <%= image_tag "avatar_placeholder.png", width: 40, height: 40, crop: :fill, class: "rounded-circle" %>
               <% end %>

             </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
<!--           <a class="dropdown-item" href="/users/<%=current_user.id%>/" style="color: darkgray; font-size: 20px;">Dashboard</a>
          <a class="dropdown-item" href="/users/edit" style="color: darkgray; font-size: 20px;">Edit Profile</a>
          <a class="dropdown-item"rel="nofollow" data-method="delete" href="/users/sign_out" style="color:darkgray; font-size: 20px;">Sign out</a>
        -->
        <%= link_to 'Dashboard', user_path(current_user), class: 'dropdown-item' %>
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </li>
  </ul>
</div>
<%end%>
</ul>
</div>
<span class="navTrigger">
 <i></i>
 <i></i>
 <i></i>
</span>
</div>
</nav>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Function used to shrink nav bar removing paddings and adding black background -->
<script>
	$(window).scroll(function() {
		if ($(document).scrollTop() > 50) {
			$('.nav.global').addClass('affix');
		} else {
			$('.nav.global').removeClass('affix');
		}
	});
</script>