config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/profile_sign_up', to: 'users/registrations#profile_sign_up', :via => [:get], :as => 'profile_sign_up'
  end
  root to: 'pages#home'
  post '/bookmark/:id' => 'offers#bookmark', as: :bookmark
  resources :offers do
    resources :inquiries do
      member do
        get 'create_chat', to: 'chatrooms#create_chatroom'
      end
      resources :interviews, only: [:new, :create]
    end
    resources :reviews
  end
  get '/users/my_interviews', to: 'interviews#my_interviews', as: :my_interviews
  get '/users/my_inquiries', to: 'inquiries#index', as: :my_inquiries
  get 'users/applications', to: 'users#job_offers', as: :business_applications
  get 'users/success', to: 'users#success', as: :inquiry_sent
  get 'users/savedoffers', to: 'users#saved_offers', as: :saved_offers
  get 'users/applications/:id/change_status', to: 'inquiries#change_status', as: :change_status
  resources :users
  resources :contact, only: [:new, :create]
  # resources :about, only: [:show]
  get 'contact_us' => 'pages#contact_us'
  resources :services, only: [:show]
  get 'services' => 'pages#services'
  get 'about' => 'pages#about', as: :about
  resources :customers, only: [:show]
  get 'customers' => 'pages#customers'
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  belongs_to :chatroom, optional: true
  has_one :interview
  has_many :reviews, dependent: :destroy
  validates :status, presence: true
  validates :message, presence: true
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy, :change_status]

  def index
    @inquiries = current_user.inquiries
  end

  def change_status
    if params[:accepted] == "true"
      @inquiry.status = "Accepted"
    else
      @inquiry.status = "Declined"
    end
    @inquiry.save
    redirect_to offer_inquiry_path(@inquiry.offer, @inquiry)
    flash.notice = "Application status changed successfully!"
  end

  def show
    @offer = Offer.find(params[:offer_id])
    if @inquiry.status == "pending"
      @inquiry.status = "opened"
      @inquiry.save
    end
  end

  def new
    @offer = Offer.find(params[:offer_id])
    @inquiry = Inquiry.new
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.user = current_user
    @inquiry.offer = @offer
    if @inquiry.save!
      redirect_to inquiry_sent_path
      flash.notice = "Your application as been sent!"
    else
      render :new
      flash.alert = "Ops! Something went wrong."
    end
  end

  def destroy
    @inquiry.destroy
    redirect_to inquiries_path
  end

  def edit
  end

  def update
    @inquiry.update(inquiry_params)
    redirect_to inquiry_path(@inquiry)
  end

  private

  def set_inquiry
    @inquiry = Inquiry.find(params[:id])
  end

  def inquiry_params
    params.require(:inquiry).permit(:status, :message, :chat)
  end
end

app/views/inquiries/index.html.erb
<div class="index-wrapper">
  <div class="list-group">
    <div class="page-header"><h2 style="text-shadow: 0px 0px 10px black;">Your job applications</h2></div>
  <% @inquiries.each do |inquiry|%>
  <div class="courses-container">
  <div class="course">
    <div class="course-preview">
      <h6>Company</h6>
      <h2><%= inquiry.offer.user.business_name %></h2>
      <a href="http://127.0.0.1:3000/offers?q%5Btitle_cont%5D=&q%5Buser_business_name_cont%5D=<%= inquiry.offer.user.business_name %>&q%5Blocation_cont%5D=&q%5Bskills_required_cont%5D=&commit=Search">View all offers from <%= inquiry.offer.user.business_name %> <i class="fas fa-chevron-right"></i></a>
    </div>
    <div class="course-info">
      <div class="progress-container">
        <span class="progress-text">
          <%= inquiry.created_at %>
        </span>
      </div>
      <h6>Job Title</h6>
      <h2><%= inquiry.offer.title %></h2>
      <h6 style="font-weight: bold;"><span class="inquiry-status">Application status: <%= inquiry.status %></span></h6>
      <%= link_to offer_inquiry_path(inquiry.offer, inquiry), class: "btn inquiry" do %>Details<%end%>
    </div>
  </div>
</div>
  <% end %>
  </div>
  </div>
</div>

app/views/inquiries/new.html.erb
<div class="device-wrapper">
  <div class="inquiry-container">
    <h3> Tell us about yourself </h3>
    <div class="form">
    <%= simple_form_for([@offer, @inquiry])do |f| %>
      <%= f.input :message, as: :text %>
      <div class="form-actions">
        <%= f.button :submit, "Apply", class: "btn btn-success btn-block" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/inquiries/show.html.erb
<div class="wrapper-offer-inquiry">
<div class="wrapper-offer-inquiry">
<div class="banner-inquiry-show">
  <div class="banner-container offers">
    <h2 style="color:white;">Hello, <%=current_user.full_name%> &#128188;</h2>
    <h4 style="color:white;">This is your applications for <%=@inquiry.offer.title%></h4>
  </div>
</div>
<div class="wrapper-inquiry app-offers-show">
    <div class="inq-offer-card">
      <div class="app-offers-card-top">
        <div class="business-logo-info">
           <img src="<%=@inquiry.user.avatar_url%>" class="logo-app-offers">
          <div class="business-info app-offers">
            <ul class="business-info">
              <li><%= @offer.user.business_name %></li>
              <li><%= @offer.user.business_address %></li>
              <li><%= @offer.user.business_size %></li>
              <li><%= @offer.user.website %></li>
              <li><%= @offer.user.linkedin_url %></li>
            </ul>
          </div>
        </div>
        <div class="app-offer-details">
        <div class="card-title">
          <h5 class="heading" style="color: black;"><%= link_to offer_path(@offer) do %>
          <%= @offer.title %>
          <% end %></h5>
        </div>
        <div class="app-offer-perks">
         <span class="badge badge-pill badge-dark ml-1 p-2"><%=@offer.employment_type%></span>
          <span class="badge badge-pill badge-dark ml-1 p-2">
          <%if @fixed_price%>Fixed Price<%else%>Per Hour<%end%></span>
         <span class="badge badge-pill badge-dark ml-1 p-2"><%=@offer.location%></span>
        </div>
        <p class="app-offers-text text-muted"><%=@inquiry.message%></p>
        </div>
      </div>
      <div class="app-offers-card-bottom">
        <%if @inquiry.chatroom%>
      <%= link_to chatroom_path(@inquiry.chatroom), class: "btn-offer btn-success btn" do %>Go to Chat<%end%>
    <%else%>
     <%= link_to create_chat_offer_inquiry_path(@inquiry.offer, @inquiry), class: "btn-offer btn-success btn" do %>Initiate Chat<%end%>
    <%end%>
    <%if @inquiry.status == "Accepted"%>
      <%= link_to new_offer_inquiry_interview_path(@inquiry.offer, @inquiry), class: "btn-offer btn-dark btn" do %>Schedule Interview<%end%>
    <%end%>
    <%if current_user.user_type == "Business" && @inquiry.status != "Accepted"%>
      <%=link_to change_status_path(@inquiry, accepted: true), class: "btn-offer btn-success btn" do%>Accept Application<%end%>
      <%=link_to change_status_path(@inquiry, accepted: false), class: "btn-offer btn-danger btn" do%>Decline Application<%end%>
    <%end%>
    <%= link_to user_path(@inquiry.user), class: "btn-offer btn-primary btn" do%>User Profile <%end%>
    </div>
      </div>
  </div>
  </div>